config/routes.rb
Rails.application.routes.draw do
  root 'themes#index'
  resources :themes, only: [:index, :create, :show, :new] do
    resources :start_times, only: :create
    resources :stop_times, only: :create
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/start_time.rb
class StartTime < ApplicationRecord
  belongs_to :theme
end

app/models/stop_time.rb
class StopTime < ApplicationRecord
  belongs_to :theme
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_one :start_time
  has_one :stop_time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @date = Date.today
  end
end

app/controllers/start_times_controller.rb
class StartTimesController < ApplicationController
  def create
    StartTime.create(start_time_params)
    redirect_to root_path
  end

  private
  def start_time_params
    params.permit(:theme_id)
  end
end

app/controllers/stop_times_controller.rb
class StopTimesController < ApplicationController
  def create
    StopTime.create(stop_time_params)
    redirect_to root_path
  end

  private
  def stop_time_params
    params.permit(:theme_id)
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def index
    @date = Date.today
    @themes = Theme.all
  end

  def new
    @themes = Theme.all
  end

  def create
    theme = Theme.create(theme_params)
    redirect_to :index
  end



  private
  def theme_params
    params.permit(:subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/start_times_helper.rb
module StartTimesHelper
end

app/helpers/stop_times_helper.rb
module StopTimesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/home/index.html.erb
<h1>hello world</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <html lang="ja">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>CLOCK</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "CLOCK", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" >
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ina 
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">マイページ</a>
          <%= link_to "学習管理ページ", new_theme_path, class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">設定</a>
        </div>
      </li>
       
    </ul>
    <div class="user_nav grid-6">
          <a class="btn btn-outline-light" href="#">新規登録</a>
          <a class="btn btn-outline-light" href="#">ログイン</a>
        </div>
  </div>
</nav>

app/views/themes/index.html.erb
<!-- Date -->
<h1><%= @date.to_formatted_s(:long)%></h1>

<!-- Digitial Clock -->
<div id="clock" class="light">
			<div class="display">
				<div class="weekdays"></div>
				<div class="ampm"></div>
				<div class="alarm"></div>
				<div class="digits"></div>
			</div>
		</div>

		<div class="button-holder">
		</div>

<!-- JavaScript Includes -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.0.0/moment.min.js"></script>

<!-- Clock-in/out -->
<%= form_with url: themes_path, method: :post do |f| %>
  <%= f.text_field :subject %>
  <%= f.submit "send", class:"btn btn-primary" %>
<% end %>

<!-- タスク一覧表示 -->
<% @themes.each do |theme| %>
  <p>タイトル<%= theme.subject %></p>
  <!-- 時間を確認したい場合は記載してください。-->
  <% if theme.start_time != nil %>
    <p>開始時刻<%= theme.start_time.created_at %></p>
  <% end %>
  <% if theme.stop_time != nil %>
    <p>終了時刻<%= theme.stop_time.created_at %></p>
  <% end %>

  <% if theme.start_time == nil %>
    <%= form_with url: theme_start_times_path(theme_id: theme.id), method: :post do |f| %>
      <%= f.submit "開始", class:"btn btn-success" %>
    <% end %>
  <% end %>

  <% if theme.start_time != nil && theme.stop_time == nil  %>
    <%= form_with url: theme_stop_times_path(theme_id: theme.id), method: :post do |f| %>
    <%= f.submit "終了", class:"btn btn-danger"%>
    <% end %>
  <% end %>

<% end %>

app/views/themes/new.html.erb
<table class="table table-striped">
  <thead >
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Subject</th>
      <th scope="col">Start Time</th>
      <th scope="col">Stop Time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @themes.subject %></td>
    </tr>
    <tr>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>